.PHONY: clean All

All:
	@echo "----------Building project:[ laba2_chast1 - Debug ]----------"
	@"$(MAKE)" -f  "laba2_chast1.mk"
clean:
	@echo "----------Cleaning project:[ laba2_chast1 - Debug ]----------"
	@"$(MAKE)" -f  "laba2_chast1.mk" clean
